### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by SENLIER** [saibalmars/GraphRicciCurvature#14]
Hi,I use the latest GraphRicciCurvature v0.4.4,the jupyter notebook demo works well.But when I try to replace Karate_club dataset with my own dataset by

`G=nx.read_adjlist("/home/seie/cora.cites")`
`print(nx.info(G))`

 I get right information:

`Name: 
Type: Graph
Number of nodes: 339
Number of edges: 457
Average degree:   2.8232`

Then,I call the method

`orc.compute_ricci_curvature()`
`G_orc = orc.G.copy()`

A error happens:
```
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/seie/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/seie/anaconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/seie/anaconda3/lib/python3.7/site-packages/GraphRicciCurvature/OllivierRicci.py", line 365, in _wrap_compute_single_edge
    return _compute_ricci_curvature_single_edge(*stuff)
  File "/home/seie/anaconda3/lib/python3.7/site-packages/GraphRicciCurvature/OllivierRicci.py", line 348, in _compute_ricci_curvature_single_edge
    x, y, d = _distribute_densities(source, target)
  File "/home/seie/anaconda3/lib/python3.7/site-packages/GraphRicciCurvature/OllivierRicci.py", line 137, in _distribute_densities
    x, source_topknbr = _get_single_node_neighbors_distributions(source, "successors")
  File "/home/seie/anaconda3/lib/python3.7/site-packages/GraphRicciCurvature/OllivierRicci.py", line 91, in _get_single_node_neighbors_distributions
    heapq.heappush(heap_weight_node_pair, (_base ** (-_get_pairwise_sp(node, nbr) ** _exp_power), nbr))
  File "/home/seie/anaconda3/lib/python3.7/site-packages/GraphRicciCurvature/OllivierRicci.py", line 198, in _get_pairwise_sp
    return _apsp[source][target]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

IndexError                                Traceback (most recent call last)
<ipython-input-183-21532f2f29e1> in <module>
----> 1 orc.compute_ricci_curvature()
      2 G_orc = orc.G.copy()  # save an intermediate result

~/anaconda3/lib/python3.7/site-packages/GraphRicciCurvature/OllivierRicci.py in compute_ricci_curvature(self)
    768                                           proc=self.proc, chunksize=self.chunksize, cache_maxsize=self.cache_maxsize,
    769                                           shortest_path = self.shortest_path,
--> 770                                           nbr_topk=self.nbr_topk)
    771         return self.G
    772 

~/anaconda3/lib/python3.7/site-packages/GraphRicciCurvature/OllivierRicci.py in _compute_ricci_curvature(G, weight, **kwargs)
    517 
    518     # compute Ricci curvature for all edges
--> 519     edge_ricci = _compute_ricci_curvature_edges(G, weight=weight, **kwargs)
    520 
    521     # Assign edge Ricci curvature from result to graph G

~/anaconda3/lib/python3.7/site-packages/GraphRicciCurvature/OllivierRicci.py in _compute_ricci_curvature_edges(G, weight, edge_list, alpha, method, base, exp_power, proc, chunksize, cache_maxsize, shortest_path, nbr_topk)
    483     # Convert edge index from nk back to nx for final output
    484     output = {}
--> 485     for rc in result:
    486         for k in list(rc.keys()):
    487             output[(nk2nx_ndict[k[0]], nk2nx_ndict[k[1]])] = rc[k]

~/anaconda3/lib/python3.7/multiprocessing/pool.py in <genexpr>(.0)
    352                     result._set_length
    353                 ))
--> 354             return (item for chunk in result for item in chunk)
    355 
    356     def apply_async(self, func, args=(), kwds={}, callback=None,

~/anaconda3/lib/python3.7/multiprocessing/pool.py in next(self, timeout)
    746         if success:
    747             return value
--> 748         raise value
    749 
    750     __next__ = next                    # XXX

IndexError: list index out of range
```

Please help me to solve this problem.

**Comment by saibalmars** [comment]
Hi, can you share the graph in gist or Pastebin so I can give it a try? 
The only cora.cites graph I can find on the Internet is with 2708 node and 5278 edges which runs no problem on my test.

**Comment by SENLIER** [comment]
Thanks,the datasets can be find in `http://networkrepository.com/citeseer.php` and `http://networkrepository.com/cora.php` The website has a lot of graph structure data.

Emmmm，I try cora.cites too，the following info Is right
`Name: Type: Graph Number of nodes: 2708 Number of edges: 5278 Average degree: 3.8981`
And it raise the totally same error
`IndexError: list index out of range`

Then I use citeseer.cites 
`Name: Type: Graph Number of nodes: 3327 Number of edges: 4676 Average degree: 2.8109`
It raise a new error
`AssertionError: Self loop is not allowed.`
But as a citation network, how can the nodes in the graph have self reference?

Can you try the above dataset？If everything goes well, would you please let me know your list of dependent package versions( e.p. numpy)?

**Comment by saibalmars** [comment]
Hi, Senlier

Can you try that on 0.4.5 to see if it solve your problem? It seems that there's a bug in 0.4.4. You can update it by typing `pip install --upgrade GraphRicciCurvature` to update to the latest 0.4.5, sorry for the inconvenient, and thanks for pointing it out.

**Comment by SENLIER** [comment]
Thanks for your advice. By upgrading package, the Cora dataset runs successfully, but the citeseer dataset still reports  a `self loop` error.I will continue to test.
