### ISSUE TITLE
IndexError: invalid index to scalar variable

### ISSUE THREAD

**Issue by andong0323** [saibalmars/GraphRicciCurvature#33]
When I run the example.py, I encounter this error:
/root/miniconda3/lib/python3.8/site-packages/ot/bregman.py:517: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn("Sinkhorn did not converge. You might want to "
/root/miniconda3/lib/python3.8/site-packages/ot/bregman.py:517: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn("Sinkhorn did not converge. You might want to "
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/root/miniconda3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/apdcephfs/share_1437072/rayan/jobs/GraphRicciCurvature/GraphRicciCurvature/OllivierRicci.py", line 352, in _wrap_compute_single_edge
    return _compute_ricci_curvature_single_edge(*stuff)
  File "/apdcephfs/share_1437072/rayan/jobs/GraphRicciCurvature/GraphRicciCurvature/OllivierRicci.py", line 333, in _compute_ricci_curvature_single_edge
    m = _sinkhorn_distance(x, y, d)
  File "/apdcephfs/share_1437072/rayan/jobs/GraphRicciCurvature/GraphRicciCurvature/OllivierRicci.py", line 250, in _sinkhorn_distance
    m = ot.sinkhorn2(x, y, d, 1e-1, method='sinkhorn')[0]
IndexError: invalid index to scalar variable.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "example.py", line 60, in <module>
    orc_Sinkhorn.compute_ricci_flow(iterations=10)
  File "/apdcephfs/share_1437072/rayan/jobs/GraphRicciCurvature/GraphRicciCurvature/OllivierRicci.py", line 801, in compute_ricci_flow
    self.G = _compute_ricci_flow(G=self.G, weight=self.weight,
  File "/apdcephfs/share_1437072/rayan/jobs/GraphRicciCurvature/GraphRicciCurvature/OllivierRicci.py", line 570, in _compute_ricci_flow
    _compute_ricci_curvature(G, weight=weight, **kwargs)
  File "/apdcephfs/share_1437072/rayan/jobs/GraphRicciCurvature/GraphRicciCurvature/OllivierRicci.py", line 504, in _compute_ricci_curvature
    edge_ricci = _compute_ricci_curvature_edges(G, weight=weight, **kwargs)
  File "/apdcephfs/share_1437072/rayan/jobs/GraphRicciCurvature/GraphRicciCurvature/OllivierRicci.py", line 475, in _compute_ricci_curvature_edges
    for rc in result:
  File "/root/miniconda3/lib/python3.8/multiprocessing/pool.py", line 448, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/root/miniconda3/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
IndexError: invalid index to scalar variable.

I can not figure out the reason, please help.

**Comment by saibalmars** [comment]
Hi thanks for the report, this is due to some api change from `POT`.
A quick and dirty fix is to roll back POT to `0.7.0` via `pip3 install pot==0.7.0`, in the meantime, I will update the code to fix that in these two days.

**Comment by saibalmars** [comment]
Fixed in #35
